# Generated by Django 2.2.28 on 2024-09-09 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201009_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('key', models.CharField(default=secrets.token_urlsafe, max_length=255, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADM', 'Admin'), ('GUE', 'Guest'), ('STU', 'Student'), ('LEC', 'Lecturer'), ('TA', 'Teaching Assistant')], default='STU', max_length=3)),
                ('valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
            ],
        ),
    ]
