# Generated by Django 5.1.1 on 2024-09-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240909_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memory_limit',
            field=models.IntegerField(default=1048576),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_image_size',
            field=models.IntegerField(default=1048576),
        ),
    ]
