# Generated by Django 5.1.1 on 2024-09-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_submission_docker_remove_submission_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='template_file',
        ),
    ]
