# Generated by Django 5.1.1 on 2024-09-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_task_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='app.task'),
        ),
    ]
