# Generated by Django 5.1.1 on 2024-09-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_course_academic_year_alter_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='partition',
        ),
        migrations.DeleteModel(
            name='Partition',
        ),
    ]
