# Generated by Django 5.1.1 on 2024-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_group_remove_invitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_files',
            field=models.BooleanField(default=True),
        ),
    ]
