# Generated by Django 5.1.1 on 2024-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_task_allow_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
