# Generated by Django 5.1.1 on 2024-10-22 13:34

import app.models.submission
import app.models.task
import app.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_task_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=app.models.submission.submission_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=app.models.utils.ExtraFileField(max_length=255, upload_to=app.models.task.task_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=app.models.task.task_path),
        ),
    ]
